/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import CallToAction from "./CallToAction";

const LandingPage: React.FC = () => {
  return (
    <main className="flex flex-col justify-center min-h-screen min-height: 100vh; p-10 font-medium text-center bg-black max-md:px-5">
      <Header />
    </main>
  );
};

export default LandingPage;
