/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ButtonProps {
  text: string;
}

const Button: React.FC<ButtonProps> = ({ text }) => {
  return (
    <button className="justify-center px-5 py-2.5 text-base font-medium leading-6 text-white bg-violet-500 rounded-lg border border-violet-500 border-solid shadow-sm">
      {text}
    </button>
  );
};

export default Button;
