/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FormInputProps {
  label: string;
  placeholder: string;
  type?: string;
}

const FormInput: React.FC<FormInputProps> = ({
  label,
  placeholder,
  type = "text",
}) => {
  return (
    <div className="mb-1 text-[#929292]">
      <label
        htmlFor={label.toLowerCase().replace(" ", "-")}
        className="block mt-6 text-sm font-medium leading-5 max-md:max-w-full"
      >
        {label}
      </label>
      <input
        type={type}
        id={label.toLowerCase().replace(" ", "-")}
        placeholder={placeholder}
        className="px-4 py-3 mt-1.5 max-w-full rounded-lg border border-solid shadow-sm bg-neutral-900 border-zinc-800 text-zinc-50 w-[480px] max-md:max-w-full"
      />
    </div>
  );
};

export default FormInput;
