/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FormInput from "./FormInput";

interface IntroduceYourselfProps {}

const IntroduceYourself: React.FC<IntroduceYourselfProps> = () => {
  const formInputs = [
    { label: "First name", placeholder: "First name" },
    { label: "Last name", placeholder: "Last name" },
    { label: "Email", placeholder: "your@email.com", type: "email" },
    { label: "Phone number", placeholder: "+62 (000) 000-0000", type: "tel" },
  ];

  return (
    <main className="flex justify-center items-center min-h-screen px-16 py-12 text-base leading-6 bg-black text-neutral-400 max-md:px-5">
      <section className="flex flex-col items-center mt-4 max-w-full w-[768px]">
        <h1 className="self-stretch text-4xl font-semibold tracking-tighter leading-10 text-center text-white max-md:max-w-full">
          Introduce Yourself
        </h1>
        <p className="self-stretch font-light mt-3 text-lg text-center max-md:max-w-full">
          We'd love to hear from you. Please fill out this form.
        </p>
        <form className="flex flex-col justify-center mt-10 max-md:mt-10">
          {formInputs.map((input, index) => (
            <FormInput key={index} {...input} />
          ))}
          <button
            type="submit"
            className="justify-center items-center px-5 py-3 mt-8 max-w-full font-medium text-white bg-violet-500 rounded-lg border border-violet-500 border-solid shadow-sm w-[480px]"
          >
            Let's Go
          </button>
        </form>
      </section>
    </main>
  );
};

export default IntroduceYourself;
